### ISSUE TITLE
v0.0.16.1.0 - Compile fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by depboy** [chaincoin/chaincoin#51]
I've tried compiling on two different machines now.  Both fail at libbitcoin_wallet_a-privatesend-client.o with the following error message:

CXX      libbitcoin_wallet_a-privatesend-client.o
privatesend-client.cpp: In member function ‘void CPrivateSendClient::ProcessMessage(CNode*, const string&, CDataStream&, CConnman*)’:
privatesend-client.cpp:57:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if(dsq.nInputCount < 0 || dsq.nInputCount > PRIVATESEND_ENTRY_MAX_SIZE)
                                                   ^
privatesend-client.cpp: In member function ‘bool CPrivateSendClient::PrepareDenominate(int, int, std::__cxx11::string&, std::vector<CTxDSIn>&, std::vector<CTxOut>&)’:
privatesend-client.cpp:1172:120: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  != nSessionDenom || (nSessionInputCount != 0 && vecTxOutRet.size() != nSession
                                                                     ^
privatesend-client.cpp: In member function ‘bool CPrivateSendClient::MakeCollateralAmounts(const CompactTallyItem&, bool, CConnman*)’:
privatesend-client.cpp:1226:15: error: no matching function for call to ‘CWalletTx::CWalletTx()’
     CWalletTx wtx;
               ^
In file included from ./privatesend-client.h:10:0,
                 from privatesend-client.cpp:4:
./wallet/wallet.h:379:5: note: candidate: CWalletTx::CWalletTx(const CWallet*, CTransactionRef)
     CWalletTx(const CWallet* pwalletIn, CTransactionRef arg) : CMerkleTx(std::m
     ^
./wallet/wallet.h:379:5: note:   candidate expects 2 arguments, 0 provided
./wallet/wallet.h:298:7: note: candidate: CWalletTx::CWalletTx(const CWalletTx&)
 class CWalletTx : public CMerkleTx
       ^
./wallet/wallet.h:298:7: note:   candidate expects 1 argument, 0 provided
./wallet/wallet.h:298:7: note: candidate: CWalletTx::CWalletTx(CWalletTx&&)
./wallet/wallet.h:298:7: note:   candidate expects 1 argument, 0 provided
privatesend-client.cpp: In member function ‘bool CPrivateSendClient::CreateDenominated(const CompactTallyItem&, bool, CConnman*)’:
privatesend-client.cpp:1393:15: error: no matching function for call to ‘CWalletTx::CWalletTx()’
     CWalletTx wtx;
               ^
In file included from ./privatesend-client.h:10:0,
                 from privatesend-client.cpp:4:
./wallet/wallet.h:379:5: note: candidate: CWalletTx::CWalletTx(const CWallet*, CTransactionRef)
     CWalletTx(const CWallet* pwalletIn, CTransactionRef arg) : CMerkleTx(std::m
     ^
./wallet/wallet.h:379:5: note:   candidate expects 2 arguments, 0 provided
./wallet/wallet.h:298:7: note: candidate: CWalletTx::CWalletTx(const CWalletTx&)
 class CWalletTx : public CMerkleTx
       ^
./wallet/wallet.h:298:7: note:   candidate expects 1 argument, 0 provided
./wallet/wallet.h:298:7: note: candidate: CWalletTx::CWalletTx(CWalletTx&&)
./wallet/wallet.h:298:7: note:   candidate expects 1 argument, 0 provided
Makefile:7770: recipe for target 'libbitcoin_wallet_a-privatesend-client.o' failed
make[2]: *** [libbitcoin_wallet_a-privatesend-client.o] Error 1
make[2]: Leaving directory '/root/chaincoin/src'
Makefile:11133: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/chaincoin/src'
Makefile:748: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by rolichain** [comment]
Can confirm same compiler error under mingw.

**Comment by chrismcna** [comment]
what git command are you using? you need to be cloning the 0.16 branch

git clone --branch "0.16" --single-branch https://github.com/chaincoin/chaincoin.git

**Comment by rolichain** [comment]
Thank you, branch 0.16 compiles.

**Comment by depboy** [comment]
cloning the 0.16 branch and following the build instructions from that branch fixed this issue for me.  Master needs updating

**Comment by chrismcna** [comment]
Master is for current development/experimental code, if you want to build for main net, never build master
